MMCU = atmega32u4
CLKSPEED = 16000000 

SRCDIR = src
INCDIR = include
BUILDFILES = build

MODULES = button
SRC = ${MODULES:=.c} main.c
OBJ = ${SRC:.c=.o}
CPPOBJ = ${addprefix ${BUILDFILES}/, ${OBJ}}

BIN = iidx
CPPBIN = ${addprefix ${BUILDFILES}/,${BIN}}
HEXFILE = ${BIN:=.hex}

CC = avr-gcc
GENFLAGS = -Wall -Os -std=c99
MMCUFLAG = -mmcu=${MMCU}
CLKFLAG = -DF_CPU=${CLKSPEED}
INCLUDEFLAG = -I${INCDIR}
FLAGS = ${GENFLAGS} ${MMCUFLAG} ${CLKFLAG} ${INCLUDEFLAG}

all : ${BUILDFILES} ${HEXFILE} 

${BUILDFILES} :
	mkdir $@

${HEXFILE} : ${CPPBIN}
	avr-objcopy -O ihex -R .eeprom $< $@
    
${CPPBIN} : ${CPPOBJ}
	${CC} ${MMCUFLAG} $^ -o $@ 

${CPPOBJ} : ${BUILDFILES}/%.o : ${SRCDIR}/%.c
	${CC} ${FLAGS} -c $< -o $@

upload : all
	./flash.sh
    
clean :
	rm -r ${HEXFILE} ${BUILDFILES}
 
hexonly : ${HEXFILE}
	rm ${BIN} ${OBJECTS}
